"""Constant classes for Ultrawide Window Positioner."""

AOT_HOTKEY = "alt + home"

class LayoutDefaults:
    """Default layouts."""

    CONFIG_HEADER_TEXT = """
# Layout configuration file
# This file is automatically generated when missing.
# Values can be edited to create additional layouts or add new overrides.
#################
# Layout:
#################
#   Auto-alignement layouts.
#     1: aspect w, aspect h, alignment for 1 window
#     2: aspect w, aspect h, alignment for 2 windows
#     3: aspect w, aspect h, left weigth for 3 windows
#     4: four window layout. For each window:
#       ( x, y ) , ( width, height )
#       Values are relative to screen size.
#
#       Example with screen resolution 5120x1440:
#       (0, 0), (0.25, 1) will be: x=0, y=0 and width=1280, height=1440
#       (0.5, 0), (0.5, 0.5) will be: x=2560, y=0 and width=2560, height=720
#################
# Overrides:
#################
#   Position and size offsets for auto-alignement.
#   Format:
#       Title = (x offset, y offset, width offset, height offset, force titlebar)
#   Examples:
#      microsoft edge = (-7, 0, 14, 7, '')
#      This will set "Microsoft Edge" to:
#      Offset 7px to the left, no offset vertically, add 14px to width and 7px to height
#      No change is made to the titlebar, so the defaults will apply
#
#      diablo iv = (0, -31, 16, 39, 'on')
#      This will set "Diablo IV" to:
#      No offset to the left, 31px up, add 16px to width and 39px to height
#      The titlebar will be forced on.

"""


    ONE_WINDOW = (
        # Format: (aspect_ratio_w, aspect_ratio_h, alignment) for 1 window
        (32, 9, "X"),
        (21, 9, "C"),
        (16, 9, "C"),
        (4, 3, "C"),

        (21, 9, "L"),
        (16, 9, "L"),
        (4, 3, "L"),

        (21, 9, "R"),
        (16, 9, "R"),
        (4, 3, "R"),
    )


    TWO_WINDOWS = (
        # Format: (aspect_ratio_w, alignment) for 2 windows
        (21, 9, "R"),
        (16, 9, "R"),
        (4, 3, "R"),

        (21, 9, "L"),
        (16, 9, "L"),
        (4, 3, "L"),

        (21, 9, "CL"),
        (16, 9, "CL"),
        (4, 3, "CL"),

        (21, 9, "CR"),
        (16, 9, "CR"),
        (4, 3, "CR"),
    )


    THREE_WINDOWS = (
        # Format: (aspect_ratio_w, aspect_ratio_h, left_weight) for 3 windows
        (21, 9, "1/2"),
        (16, 9, "1/2"),
        (4, 3, "1/2"),

        (21, 9, "2/3"),
        (16, 9, "2/3"),
        (4, 3, "2/3"),

        (21, 9, "3/5"),
        (16, 9, "3/5"),
        (4, 3, "3/5"),

        (21, 9, "2/5"),
        (16, 9, "2/5"),
        (4, 3, "2/5"),

        (21, 9, "1/3"),
        (16, 9, "1/3"),
        (4, 3, "1/3"),
    )


    FOUR_WINDOWS = (
        # layout 0: four equal horizontal windows
        (
            ((0, 0), (1/4, 1)),
            ((1/4, 0), (1/4, 1)),
            ((1/2, 0), (1/4, 1)),
            ((3/4, 0), (1/4, 1)),
        ),

        # layout 1: 1 & 2 stacked left half, 3 & 4 side-by-side on right half
        (
            ((0, 0), (1/2, 1/2)),
            ((0, 1/2), (1/2, 1/2)),
            ((1/2, 0), (1/4, 1)),
            ((3/4, 0), (1/4, 1)),
        ),

        # layout 2: 1 & 2 side-by-side left half, 3 & 4 stacked right half
        (
            ((0, 0), (1/4, 1)),
            ((1/4, 0), (1/4, 1)),
            ((1/2, 0), (1/2, 1/2)),
            ((1/2, 1/2), (1/2, 1/2)),
        ),

        # layout 3: four equally sized 2x2 grid
        (
            ((0, 0), (1/2, 1/2)),
            ((1/2, 0), (1/2, 1/2)),
            ((0, 1/2), (1/2, 1/2)),
            ((1/2, 1/2), (1/2, 1/2)),
        ),
    )


    OVERRIDES = (
        # Title, x offset, y offset, width offset, height offset, force titlebar
        # The "force titlebar" value will set the titlebar value on or off regardless
        # of the typical auto-align value.
        ("Opera", (-7, 0, 14, 7, "")),
        ("Microsoft Edge", (-7, 0, 14, 7, "")),
        ("Discord", (-2, -1, 3, 0, "")),
        ("Visual Studio Code", (0, -1, 0, 0, "")),
        ("Diablo IV", (0, -31, 16, 39, "on")),
        )

class UIConstants:
    """GUI constant values."""

    # Window dimensions
    WINDOW_WIDTH = 750
    WINDOW_HEIGHT = 540
    WINDOW_MIN_WIDTH = 750
    WINDOW_MIN_HEIGHT = 540

    SETTINGS_WIDTH = 900
    SETTINGS_HEIGHT = 500

    COMPACT_WIDTH = 200
    COMPACT_HEIGHT = 530

    BUTTON_WIDTH = 120
    BUTTON_HEIGHT = 40
    COMPACT_BUTTON_WIDTH = 80
    CANVAS_HEIGHT = 240
    TASKBAR_HEIGHT = 46
    MAX_WINDOWS = 4
    WINDOW_TITLE_MAX_LENGTH = 24

    # UI element sizes
    MARGIN = (2,2,2,2)  # (top, right, bottom, left)
    PADDING = 0
    LINE_HEIGHT = 20
    FONT_SIZE = 8
    MANAGED_WINDOWS_WIDTH = 165
    MANAGED_WINDOWS_HEIGHT = (FONT_SIZE + 12) * MAX_WINDOWS
    CONFIG_DROPDOWN_WIDTH = 250
    LABEL_WIDTH = 60

    # Layout constants
    DEFAULT_ALIGN = "center"  # Valid values: 'left', 'center', 'right'
    DEFAULT_DIRECTION = "column"  # Valid values: 'row', 'column'

class Colors:
    """GUI color values."""

    # Background colors
    BACKGROUND = "#202020"
    TASKBAR = "#666666"

    # Window colors
    WINDOW_NORMAL = "#404040"
    WINDOW_ALWAYS_ON_TOP = "#306030"
    WINDOW_BORDER = "#050505"
    WINDOW_FRAME = "#101010"
    DIM_BORDER = "#555555"

    # Window styles
    TITLE_BAR_COLOR = "#000000"
    TITLE_TEXT_COLOR = "#FFFFFF"
    BORDER_COLOR = "#101010"

    # Text colors
    TEXT_NORMAL = "#FFFFFF"
    TEXT_ERROR = "#FFFF00"
    TEXT_ALWAYS_ON_TOP = "#50A050"
    TEXT_DIM = "#555555"

    # Use these for darker backgrounds
    WINDOW_NORMAL_DARK = "#2A2A2A"
    WINDOW_ALWAYS_ON_TOP_DARK = "#104010"
    WINDOW_MISSING_DARK = "#3F1F1F"

    # Buttons
    BUTTON_NORMAL = "#303030"
    BUTTON_HOVER = "#505050"
    BUTTON_ACTIVE = "#206020"
    BUTTON_ACTIVE_HOVER = "#408040"
    BUTTON_DISABLED = WINDOW_NORMAL_DARK

    # Status colors
    ADMIN_ENABLED = "#308030"
    ADMIN_DISABLED = "#803030"

class Messages:
    """GUI messages."""

    # Status messages
    CLICK_TARGET = "Click on the target window..."
    WINDOW_SELECT_FAILED = "Window selection failed or cancelled."
    ALWAYS_ON_TOP_DISABLED = "AOT: None"
    SELECT_CONFIG = "Select a configuration"

    # Error messages
    ERROR_TOO_MANY_WINDOWS = f"Please select {UIConstants.MAX_WINDOWS} or fewer windows"
    ERROR_NO_WINDOWS = "Please select at least one window"
    ERROR_NO_APP = "Error: Application reference not set"
    ERROR_TOGGLE_COMPACT = "Error toggling compact mode: {}"
    ERROR_GUI_CREATION = "Error creating GUI: {}"
    ERROR_NO_CONFIG = "No config found"

class Fonts:
    """GUI fonts."""

    TEXT_TITLE = ("Consolas", 11, "bold")
    TEXT_NORMAL = ("Consolas", 10, "normal")
    TEXT_BOLD = ("Consolas", 10, "bold")
    TEXT_SMALL = ("Consolas", 8, "normal")
