"""Constant classes for Ultrawide Window Positioner."""

AOT_HOTKEY = "alt+home"

IGNORED_WINDOWS = [
            "ultrawide window positioner",
            "program manager",
            "windows input experience",
            "microsoft text input application",
            "settings",
            "windows shell experience host",
            ]


class LayoutDefaults:
    """Default layouts."""

    CONFIG_HEADER_TEXT = """
# Layout configuration file
# This file is automatically generated when missing.
# Values can be edited to create additional layouts or add new overrides.
#################
# Layout:
#################
#   Auto-alignment layouts.
#     1: aspect w, aspect h, alignment for 1 window
#     2: aspect w, aspect h, alignment for 2 windows
#     3: aspect w, aspect h, left weight for 3 windows
#     4: four window layout. For each window:
#       ( x, y ) , ( width, height )
#       Values are relative to screen size.
#
#       Example with screen resolution 5120x1440:
#       (0, 0), (0.25, 1) will be: x=0, y=0 and width=1280, height=1440
#       (0.5, 0), (0.5, 0.5) will be: x=2560, y=0 and width=2560, height=720
#################
# Overrides:
#################
#   Position and size offsets for auto-alignment.
#   Format:
#       Title = (x offset, y offset, width offset, height offset, force titlebar)
#   Examples:
#      microsoft edge = (-7, 0, 14, 7, '')
#      This will set "Microsoft Edge" to:
#      Offset 7px to the left, no offset vertically, add 14px to width and 7px to height
#      No change is made to the titlebar, so the defaults will apply
#
#      diablo iv = (0, -31, 16, 39, 'on')
#      This will set "Diablo IV" to:
#      No offset to the left, 31px up, add 16px to width and 39px to height
#      The titlebar will be forced on.

"""


    ONE_WINDOW = (
        # Format: (aspect_ratio_w, aspect_ratio_h, alignment) for 1 window
        (32, 9, "X"),
        (21, 9, "C"),
        (16, 9, "C"),
        (4, 3, "C"),

        (21, 9, "L"),
        (16, 9, "L"),
        (4, 3, "L"),

        (21, 9, "R"),
        (16, 9, "R"),
        (4, 3, "R"),
    )


    TWO_WINDOWS = (
        # Format: (aspect_ratio_w, alignment) for 2 windows
        (21, 9, "R"),
        (16, 9, "R"),
        (4, 3, "R"),

        (21, 9, "L"),
        (16, 9, "L"),
        (4, 3, "L"),

        (21, 9, "CL"),
        (16, 9, "CL"),
        (4, 3, "CL"),

        (21, 9, "CR"),
        (16, 9, "CR"),
        (4, 3, "CR"),
    )


    THREE_WINDOWS = (
        # Format: (aspect_ratio_w, aspect_ratio_h, left_weight) for 3 windows
        (21, 9, "1/2"),
        (16, 9, "1/2"),
        (4, 3, "1/2"),

        (21, 9, "2/3"),
        (16, 9, "2/3"),
        (4, 3, "2/3"),

        (21, 9, "3/5"),
        (16, 9, "3/5"),
        (4, 3, "3/5"),

        (21, 9, "2/5"),
        (16, 9, "2/5"),
        (4, 3, "2/5"),

        (21, 9, "1/3"),
        (16, 9, "1/3"),
        (4, 3, "1/3"),
    )


    FOUR_WINDOWS = (
        # layout 0: four equal horizontal windows
        (
            ((0, 0), (1/4, 1)),
            ((1/4, 0), (1/4, 1)),
            ((1/2, 0), (1/4, 1)),
            ((3/4, 0), (1/4, 1)),
        ),

        # layout 1: 1 & 2 stacked left half, 3 & 4 side-by-side on right half
        (
            ((0, 0), (1/2, 1/2)),
            ((0, 1/2), (1/2, 1/2)),
            ((1/2, 0), (1/4, 1)),
            ((3/4, 0), (1/4, 1)),
        ),

        # layout 2: 1 & 2 side-by-side left half, 3 & 4 stacked right half
        (
            ((0, 0), (1/4, 1)),
            ((1/4, 0), (1/4, 1)),
            ((1/2, 0), (1/2, 1/2)),
            ((1/2, 1/2), (1/2, 1/2)),
        ),

        # layout 3: four equally sized 2x2 grid
        (
            ((0, 0), (1/2, 1/2)),
            ((1/2, 0), (1/2, 1/2)),
            ((0, 1/2), (1/2, 1/2)),
            ((1/2, 1/2), (1/2, 1/2)),
        ),
    )


    OVERRIDES = (
        # Title, x offset, y offset, width offset, height offset, force titlebar
        # The "force titlebar" value will set the titlebar value on or off regardless
        # of the typical auto-align value.
        ("Opera", (-7, 0, 14, 7, "")),
        ("Microsoft Edge", (-7, 0, 14, 7, "")),
        ("Discord", (-2, -1, 3, 0, "")),
        ("Visual Studio Code", (0, -1, 0, 0, "")),
        ("Diablo IV", (0, -31, 16, 39, "on")),
        )

class UIConstants:
    """GUI constant values."""

    # Window dimensions
    WINDOW_WIDTH = 800
    WINDOW_HEIGHT = 600
    WINDOW_MIN_WIDTH = 800
    WINDOW_MIN_HEIGHT = 600

    COMPACT_WIDTH = 200
    COMPACT_HEIGHT = 470

    TASKBAR_HEIGHT = 46
    MAX_WINDOWS = 4
    WINDOW_TITLE_MAX_LENGTH = 24

class Colors:
    """GUI color values."""

    # Background colors
    BACKGROUND = "#202020"
    TASKBAR = "#666666"

    # Window colors
    WINDOW_NORMAL = "#404040"
    WINDOW_ALWAYS_ON_TOP = "#306030"
    WINDOW_BORDER = "#050505"
    WINDOW_FRAME = "#101010"

    BORDER_COLOR = WINDOW_FRAME

    # Text colors
    TEXT_NORMAL = "#FFFFFF"
    TEXT_ERROR = "#FF6B6B"
    TEXT_ALWAYS_ON_TOP = "#50A050"
    TEXT_NOTICE = "#907000"

    # Buttons
    BUTTON_NORMAL = "#303030"
    BUTTON_HOVER = "#505050"
    BUTTON_ACTIVE = "#206020"
    BUTTON_ACTIVE_HOVER = "#408040"
    BUTTON_NOTICE = "#907000"
    BUTTON_DISABLED = "#2A2A2A"

class Messages:
    """GUI messages."""

    # Status messages
    ALWAYS_ON_TOP_DISABLED = "AOT: None"

class Fonts:
    """GUI fonts."""

    TEXT_NORMAL = ("Consolas", 10, "normal")
    TEXT_SMALL = ("Consolas", 8, "normal")

